---
title: "Public Health Data Science"
output: html_document
---

Although the major components of data science have existed for many years, the term has rapidly grown in prominence in the last decade. This reflects the confluence of several important trends in science, including the prevalence of big data, the development of computational approaches to analysis, and the recognized need for reproducibility in research. We'll provide an understanding of “data science”, with particular emphasis on connotation and the implied perspectives for working with data. We'll then consider the ongoing dialog between public health and data science, and suggest ways that public health data science might evolve and drive innovation in coming years. 

<script async class="speakerdeck-embed" data-id="d6a0bc462ce14417a88bf41ff6148590" data-ratio="1.77777777777778" src="//speakerdeck.com/assets/embed.js"></script>
<div style="margin-bottom:5px"> <strong> <a href="https://speakerdeck.com/jeffgoldsmith/aphrea-phds" title="APHREA: PHDS" target="_blank">APHREA: PHDS</a> </strong> from <strong><a href="https://speakerdeck.com/jeffgoldsmith" target="_blank">Jeff Goldsmith</a></strong>. </div>

Slides can be downloaded [here](./slides/ShortCourse_PHDS.pdf).

The paper on which this talk is based can be accessed [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8378512/). 
